version: '3.7'

services:
  vue-starter:
    container_name: vue-starter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - "8080:8080"
    network_mode: host
